### ISSUE TITLE
Add LZO compression in Snap

### ISSUE THREAD

**Issue by soumyaDghosh** [headsetapp/headset-snap#6]
After installing the headset snap, I checked that compression isn't mentioned there. Mention `compression: lzo` in the `snapcraft.yaml` file and the startup speed will increase a lot. I didn't get the snapcraft.yaml in your repo, else I'd have pushed that.

**Comment by fcastilloec** [comment]
Hi, thanks for pointing it out. I wasn't aware that the compression will increase startup speed.
If you want to submit a PR for this, here's the repo for our snap:

https://github.com/headsetapp/headset-snap

**Comment by soumyaDghosh** [comment]
Let me explain it to you how, Currently by default snaps uses tar.xz compression. which uses high compression, so, the .snap file is small, but it takes more time to extract that. But with LZO, the compression is less, so, the snap file is slightly bigger, but the compression is less.

**Comment by soumyaDghosh** [comment]
Hey, I just updated the app, the startup speed is 1 sec, compared to 4.99 sec. What about you? Can u check it?

**Comment by fcastilloec** [comment]
That is great news! I only use the `.deb` for my own, so I'm going to need to spin a virtual machine so I can test it.
I was reading more about LZO compression and indeed, it can offer 2-3 times speed improvement, so it makes sense to see such a big change. Just make sure you test the startup times on a freshly rebooted system because after the first time opened, data is cached in memory and subsequent starts are always fast no matter the compression algorithm.

**Comment by soumyaDghosh** [comment]
The cache should be same for both the revisions. And snaps are a little different. When they are invoked, they are actually mounted, like a disk. Anyways tested after reboot. 4 sec on the latest one. With cache, the last revision was almost 5 sec.
